{{- $fullName := include "hyperf.fullname" . -}}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default $fullName .name }}
  labels:
    {{- include "hyperf.server.labels" . | nindent 4 }}
spec:
  type: {{ default "ClusterIP" .type }}
  ports:
    {{ range .ports }}
    - port: {{ default 80 .port }}
      targetPort: {{ default "http" .targetPort }}
      protocol: {{ default "TCP" .protocol }}
      name: {{ default "http" .name }}
    {{- end }}
  selector:
    {{- include "hyperf.server.selectorLabels" . | nindent 4 }}
{{- end  }}
