nameOverride: ""
fullnameOverride: ""

image:
  repository: pandawa/pandawa
  pullPolicy: IfNotPresent
  tag: ""

init:
  enabled: true
  command: ["php", "bin/hyperf.php"]
  args:
    - "migrate"
    - "--force"
  resources: {}
  podAnnotations: {}

services:
  - name: ""
    type: ClusterIP
    ports:
      - port: 80
        targetPort: http
        protocol: TCP
        name: http

server:
  enabled: true
  replicaCount: 1
  command: ["php", "bin/hyperf.php"]
  args:
    - "start"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    behavior:
      scaleDown:
        stabilizationWindowSeconds: 600
        policies:
          - type: Percent
            value: 10
            periodSeconds: 60
  sidecars: []
  volumes: []
  volumeMounts: []
  resources: {}
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  nodeSelector: {}
  affinity: {}
  tolerations: []
  topologySpreadConstraints: []

serviceAccount:
  create: false
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
          serviceName: ""
          servicePort: ""
  tls: []
  stripPrefixes: []

env: ""

configEnv: {}

secretEnv: {}

imagePullSecrets: []
